spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  web:
    resources:
      cache:
        period: 0
      static-locations:
        - classpath:/static/
    locale: en_US
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
  application:
    name: cinema-booking-monolith
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema_booking
    username: cinema_user
    password: cinema_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
cinema:
  upload-dir: ${user.dir}/uploads
  cleaning-duration-minutes: 25
  reservation-expiration-minutes: 15

server:
  tomcat:
    max-http-form-post-size: 52428800
    max-part-count: 50
    max-part-header-size: 2048
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE